================================================================================
Test for ./d4_2_tests_program/test1.py and 2, 4:
                 Successful - True, Time - 1.605278491973877, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 61, 10:
                 Successful - True, Time - 1.6919667720794678, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 2, 96:
                 Successful - True, Time - 1.771108627319336, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 55.0, 12.0:
                 Successful - True, Time - 1.6832911968231201, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 4, 2:
                 Successful - True, Time - 1.81028151512146, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 56, 21:
                 Successful - True, Time - 1.8418982028961182, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 41, 7:
                 Successful - True, Time - 1.8357815742492676, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 43, 14:
                 Successful - True, Time - 1.8783888816833496, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 81, 38:
                 Successful - True, Time - 1.90887451171875, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 15, 52:
                 Successful - True, Time - 1.8290729522705078, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 42, 19:
                 Successful - True, Time - 1.8783342838287354, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test1.py and 13, 51:
                 Successful - True, Time - 1.924753189086914, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 31.0, 53.0:
                 Successful - True, Time - 1.8657710552215576, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 49.0, 99.0:
                 Successful - True, Time - 1.863070011138916, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 85.0, 13.0:
                 Successful - True, Time - 1.8365228176116943, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 23.0, 41.0:
                 Successful - True, Time - 1.7896685600280762, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 27.0, 15.0:
                 Successful - True, Time - 1.898831844329834, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 31.0, 4.0:
                 Successful - True, Time - 1.7918221950531006, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 99.0, 39.0:
                 Successful - True, Time - 1.943392276763916, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 73.0, 30.0:
                 Successful - True, Time - 1.8802626132965088, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test3.py and asdasda, adfsdfa:
                 Successful - False, Time - 0.7233109474182129, Status - Wrong answer.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test5.py and 2, 3:
                 Successful - False, Time - 0.6411309242248535, Status - Wrong answer.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test2.py and 22.0, 19.0:
                 Successful - True, Time - 0.8782565593719482, Status - Accepted.
================================================================================

================================================================================
Test for ./d4_2_tests_program/test4.py and 2, 3:
                 Successful - False, Time - 2, Status - Time limit exceeded.
================================================================================

